concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  linkcheck:
    name: Sphinx linkcheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - continue-on-error: true
      name: Install dependencies
      run: 'python -m pip install --upgrade pip setuptools

        python -m pip install -r blackbox/requirements.txt

        '
    - continue-on-error: true
      name: Run linkcheck
      run: 'sphinx-build -n -W --keep-going -q -c docs/ -b linkcheck -E docs/ docs/out/html

        '
  vale:
    name: Vale
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      name: Run vale
      uses: errata-ai/vale-action@v2.1.0
      with:
        files: docs/
        version: 3.4.1
name: CrateDB Docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
