jobs:
  automate-project:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.JENKINS_USER_TOKEN }}
        PR_ID: ${{github.event.pull_request.node_id}}
      name: Add PR to CrateDB project board
      run: "gh api graphql -F contentId=$PR_ID -f query='\n  mutation($contentId:\
        \ ID!) {\n    addProjectV2ItemById(input: {projectId: \"PVT_kwDOAD3FaM4ACoUS\"\
        \ contentId: $contentId}) {\n      item {\n        id\n      }\n    }\n  }\n\
        \  '"
name: Add PR to CrateDB project board
on:
  repository_dispatch:
    types: trigger-ga___project.yml
