jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Repository checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Differential ShellCheck
      uses: redhat-plumbers-in-action/differential-shellcheck@v3
      with:
        severity: warning
        token: ${{ secrets.GITHUB_TOKEN }}
name: Differential ShellCheck
on:
  repository_dispatch:
    types: trigger-ga___shellcheck.yml
permissions:
  contents: read
